from enum import Enum

class DeploymentProfile(str, Enum):
    MULTISPECIALTY_TERTIARY_CENTER = "MULTISPECIALTY_TERTIARY_CENTER"
    RURAL_PRIMARY_HEALTH_CENTRE = "RURAL_PRIMARY_HEALTH_CENTRE"

class PermissionToken(str, Enum):
    BED_MANAGEMENT_SYSTEM = "BED_MANAGEMENT_SYSTEM"
    STAFF_ROSTER_DB = "STAFF_ROSTER_DB"
    INSTRUMENT_INVENTORY = "INSTRUMENT_INVENTORY"

SUPPORTED_DAILY_ED_MIN = 100
REFERENCE_DAILY_ED_MAX = 500
EXPECTED_HISTORY_RATIO = 0.50

ALLOWED_MANUAL_ENTRY_CATEGORIES = {
    "VITAL_SIGNS",
    "CLINICAL_NARRATIVE",
    "IMAGING_METADATA",
}

